### PR TITLE
Update to write function to work with pgx4 and higher

### PR DESCRIPTION
**Pull request by hlcianfagna**
## Summary of the changes / Why this is an improvement

Update to write function to work with pgx4

Closes: #88

## Checklist

 - [X] Link to issue this PR refers to (if applicable): 
 - [X] [CLA](https://crate.io/community/contribute/cla/) is signed

### CODE REVIEW

**Comment by hammerhead** [comment]
I gave the patch a try but still ran into the originally reported error message.
In the [pgx documentation](https://pkg.go.dev/github.com/jackc/pgx/v5#hdr-Prepared_Statements) I then found a note that using prepared statements is typically not necessary anymore, which seems to be new in v5:
> However, this is rarely necessary because pgx includes an automatic statement cache by default

After replacing the prepared statement with a regular batched insert, I ran into `error closing write batch: context deadline exceeded`. A fix for that was to comment out this line:

https://github.com/crate/cratedb-prometheus-adapter/blob/2f9832896e1b4113ca6f3168d8f15c0160c52505/crate.go#L219

Only after that, I could see data arriving in the target table. But I'm not deep enough into pgx to really understand the details of the `WithTimeout` "fix".

**Comment by hlcianfagna** [comment]
I got this working now in my test environment, could you take another look at it @hammerhead ?

**Comment by hammerhead** [comment]
Looks good from a functional perspective. When running `go run . -config.file ../config.yml` on that branch, I can see data coming in successfully 👍.

**Comment by hlcianfagna** [comment]
I also looked at the possibility of adding a test case to test this function but it seems `pgxmock` would not currently support this ( https://github.com/pashagolub/pgxmock/discussions/152 )

**Comment by amotl** [comment]
Hi. Thank you so much for discovering the root cause of GH-88, and for submitting this patch and confirming it works well. I think it will be good to merge it without further ado.

**Review by amotl — APPROVED** [review]
Acknowledged, thank you. 💯

**Pull request merged**
